--- 
- hosts: 172.31.59.154
  become: yes
  gather_facts: yes
  tasks: 
    - name: run a cmd 
      command: date 
      register: display
      tags: name1

    - name: run a cmd-2 
      command: dateee 
      register: display

      ignore_errors: True

    - name: display result 
      debug:
         msg: "{{display}}"

    - name: install git
      apt:
         name: git
         state: present 
      when: display.failed == false

    - name: install wget
      apt:
         name: wget
         state: present 
      when: display.failed == true