--- 
- hosts: 172.31.59.154
  become: yes
  gather_facts: yes
  tasks: 
    - name: run a cmd 
      command: date 
      register: display

    - name: display result 
      debug:
         msg: "{{display}}"