--- 
- hosts: 172.31.59.154
  become: yes
  gather_facts: yes
  tasks: 
    - name: install git
      apt:
        name: gittttt
        state: present
      ignore_errors: True  

    - name: installl tree 
      apt:
        name: tree 
        state: present 
    
    - name: run the linux cmd hostname 
      command: hostname -f 
      register: result 

    - name: display the output of result 
      debug:
         msg: "{{result}}"
     
