--- 
- hosts: all 
  become: yes 
  tasks: 
    - name: i want to install webserver
      apt:
       name: apache2
       state: present 
    - name: i want install git 
      apt:
       name: git
       state: present
      when: ansible_os_family:"Debian"