--- 
- hosts: webservers
  become: yes
  gather_facts: yes
  tasks:
    - name: install ansible or python
      apt:
       name: "{{var11}}"
       state: present
      when: ansible_os_family == "Debian"

    - name: display result 
      debug:
        msg: "{{var11}}"
      