--- 
- hosts: ubuntuserver
  become: yes
  gather_facts: yes
  tasks: 
     - name: run the linux cmd hostname 
       command: hostname -f 
       register: result 

     - name: display the output of result 
       debug:
         msg: "{{result}}"

     - name: install git 
       apt: 
         name: git 
       when: result.stderr == " "

     - name: install tree 
       apt:
         name: tree 
       when: result.stderr != " "