--- 
- hosts: webservers 
  become: yes
  gather_facts: yes
  tasks: 
   - name: i want to install webserver on ubuntu node
     apt:
       name: "{{ubuntuvar}}"
       state: present
     when: ansible_os_family == "Debian"

   - name: start webserver on ubuntu
     service:
        name: "{{ubuntuvar}}"
        state: started
     when: ansible_os_family == "Debian"

   - name: i want to install webserver on RedHat node
     yum:
       name: "{{redhatvar}}"
       state: present 
     when: ansible_os_family == "RedHat"

   - name: start webserver on redhat 
     service:
         name: "{{redhatvar}}"
         state: started
     when: ansible_os_family == "RedHat"